// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for about documents */
interface AboutDocumentData {
  /**
   * linkedin field in *about*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about.linkedin
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  linkedin: prismic.LinkField;
  /**
   * youtube field in *about*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about.youtube
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  youtube: prismic.LinkField;
  /**
   * github field in *about*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about.github
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  github: prismic.LinkField;
  /**
   * content field in *about*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismic.RichTextField;
}
/**
 * about document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AboutDocumentData>, "about", Lang>;
/** Content for skils documents */
interface SkilsDocumentData {
  /**
   * title field in *skils*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skils.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * description field in *skils*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skils.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
  /**
   * skils field in *skils*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: skils.skils[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  skils: prismic.GroupField<Simplify<SkilsDocumentDataSkilsItem>>;
}
/**
 * Item in skils → skils
 *
 */
export interface SkilsDocumentDataSkilsItem {
  /**
   * title field in *skils → skils*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skils.skils[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismic.KeyTextField;
  /**
   * description field in *skils → skils*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: skils.skils[].description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismic.RichTextField;
  /**
   * ability level field in *skils → skils*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: skils.skils[].ability_level
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  ability_level: prismic.NumberField;
  /**
   * icon field in *skils → skils*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: skils.skils[].icon
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  icon: prismic.ImageField<never>;
  /**
   * tech color field in *skils → skils*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: skils.skils[].tech_color
   * - **Documentation**: https://prismic.io/docs/core-concepts/color
   *
   */
  tech_color: prismic.ColorField;
}
/**
 * skils document from Prismic
 *
 * - **API ID**: `skils`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SkilsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SkilsDocumentData>, "skils", Lang>;
export type AllDocumentTypes = AboutDocument | SkilsDocument;
/**
 * Primary content in Teste → Primary
 *
 */
interface TesteSliceDefaultPrimary {
  /**
   * content field in *Teste → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: teste.primary.content
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismic.RichTextField;
  /**
   * image field in *Teste → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: teste.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismic.ImageField<never>;
}
/**
 * Default variation for Teste Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TesteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TesteSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Teste*
 *
 */
type TesteSliceVariation = TesteSliceDefault;
/**
 * Teste Shared Slice
 *
 * - **API ID**: `teste`
 * - **Description**: `Teste`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TesteSlice = prismic.SharedSlice<"teste", TesteSliceVariation>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      AboutDocumentData,
      AboutDocument,
      SkilsDocumentData,
      SkilsDocumentDataSkilsItem,
      SkilsDocument,
      AllDocumentTypes,
      TesteSliceDefaultPrimary,
      TesteSliceDefault,
      TesteSliceVariation,
      TesteSlice,
    };
  }
}
